security:
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: /admin/login
                check_path: /admin/login_check
                always_use_default_target_path: false
                default_target_path: /admin/dashboard
            logout:
                path: /admin/logout
            anonymous:    true

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_MANAGER
        ROLE_SUPER_ADMIN: ROLE_ADMIN


    access_control:
       #- { path: ^/admin/, role: ROLE_ADMIN }
       # - { path: ^/admin/, role: ROLE_MANAGER }
       - { path: ^/admin/user-manager, role: ROLE_ADMIN }
